services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
      - "${NETWORK_ADDRESS}:5000:5000"
      - "${VPN_ADDRESS}:5000:5000"
    volumes:
      - ./backend:/app
      - ./alpaca.db:/app/alpaca.db
    environment:
      ALPACA_DB_PATH: "/app/alpaca.db"
      TTS_SERVER_URL: "http://kokoro:8880"
      TTS_API_KEY: ${KOKORO_API_KEY}
      CORS_DOMAINS: "${CORS_DOMAINS}"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
      - "${NETWORK_ADDRESS}:3000:3000"
      - "${VPN_ADDRESS}:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always

  kokoro:
    container_name: kokoro
    image: hwdsl2/kokoro-server
    ports:
      - "127.0.0.1:8880:8880"
      - "${NETWORK_ADDRESS}:8880:8880"
      - "${VPN_ADDRESS}:8880:8880"
    volumes:
      - kokoro-data:/var/lib/kokoro
    environment:
      KOKORO_API_KEY: ${KOKORO_API_KEY}
    restart: always

volumes:
  kokoro-data:
