services:
  backend:
    container_name: walpaca_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
      - "${NETWORK_ADDRESS}:5000:5000"
      - "${VPN_ADDRESS}:5000:5000"
    volumes:
      - ./backend:/app
      - ./alpaca.db:/app/alpaca.db
      - ./personas:/app/personas
      - ./lorebook:/app/lorebook
      - ./config:/app/config
    environment:
      ALPACA_DB_PATH: "/app/alpaca.db"
      TTS_SERVER_URL: "http://kokoro:8880"
      TTS_API_KEY: ${KOKORO_API_KEY}
      CORS_DOMAINS: "${CORS_DOMAINS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"
    restart: always

  frontend:
    container_name: walpaca_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
      - "${NETWORK_ADDRESS}:3000:3000"
      - "${VPN_ADDRESS}:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      CORS_DOMAINS: "${CORS_DOMAINS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"
    restart: always
    command: npm run dev

  kokoro:
    container_name: walpaca_kokoro
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest # or -gpu
    ports:
      - "127.0.0.1:8880:8880"
      - "${NETWORK_ADDRESS}:8880:8880"
      - "${VPN_ADDRESS}:8880:8880"
    volumes:
      - kokoro-data:/var/lib/kokoro
      - kokoro_cache:/root/.cache/huggingface
    environment:
      KOKORO_API_KEY: ${KOKORO_API_KEY}
      HF_HUB_OFFLINE: 0 # 0 = Allows downloads, 1 = Offline mode
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"
    restart: always

volumes:
  kokoro-data:
  kokoro_cache:
